### ISSUE TITLE
Upper/lower case compatibility and duplicate-prefix/redundant arguments

### ISSUE THREAD

**Issue by Criss-Wang** [AY2021S1-CS2103-W14-4/tp#122]
Just some quick thought about the general command string that could lead to potential bugs:

* Shall we allow uppercase/lowercase conversion in parsing or shall we restrict command string to be case-sensitive?
* I notice that the test covers some cases where the command has multiple same prefixes (e.g `update w/WarehouseA w/WarehouseB pd/Panadol q/10 q/12`). Shall we allow this behaviour? If so which entry shall we keep?
* Another issue could be the entry of redundant arguments (`delete supplier 1 *some random string` will pass the test). Shall we allow this behaviour as well?

**Comment by jeffreytjs** [comment]
Good thoughts, I believe handling upper/lower case conversion on our end would improve user experience instead of making it case-sensitive. Especially when they are not able to correct minor typo by retrieving last typed command using the up arrow key like we do in terminals. 

You're right, I just tried for add command and it process everything but only keeps the results from the last occurrence. This is a bug and should be resolved unless a command explicitly takes in 2 of the same prefix. Good catch Zhen Lin.

I would think that redundant arguments can be safely ignored if they do not interfere with the given command. We can set up a response that notify them of the `random string` while letting the command run through. This would be even more useful when we implement undo and redo commands.

**Comment by Criss-Wang** [comment]
> Good thoughts, I believe handling upper/lower case conversion on our end would improve user experience instead of making it case-sensitive. Especially when they are not able to correct minor typo by retrieving last typed command using the up arrow key like we do in terminals.
> 
> You're right, I just tried for add command and it process everything but only keeps the results from the last occurrence. This is a bug and should be resolved unless a command explicitly takes in 2 of the same prefix. Good catch Zhen Lin.
> 
> I would think that redundant arguments can be safely ignored if they do not interfere with the given command. We can set up a response that notify them of the `random string` while letting the command run through. This would be even more useful when we implement undo and redo commands.

Thanks Jeffery for the response!

* For the first point, I guess if we all agree on this, we can discuss in chat about the implementation detail (like whether to handle it in general parserUtil or somewhere else)
* For the second point, thanks and I'm guessing we also need to mention this in our user guide & Usage message if we treat this issue as a bug.
* For the third point, I think your suggestion is wonderful! We can also discuss later about the message format, etc.

**Comment by tohyuting** [comment]
Thanks for pointing them out! I agree with Jeffrey on the third point as well, I think it would improve user experience if we let for instance a delete command with random string at the back to pass through rather than forcing the user to re-enter the command without the random string. 

As for the first point, may I clarify if you meant for e.g. add vs Add (or any other variations of add) in the case of command string to be insensitive?

Also, another bug I noticed was for delete, find and view, the ordering of arguments matter. In our user guide, it was mentioned that parameters can be in any order. However, without any delimiter in place, like t/TYPE, it will be hard for us to ascertain which word is for type and which word is for name of supplier/warehouses (in the case of find and view). I was thinking if we should specify that ordering does not matter for all commands except delete, find and view in our user guide to be clear. 

EDIT:
Just to add on, the current way of handling adding of suppliers and warehouses has a bug since type of determined by doing a substring of trimmed arguments. If users are allowed to reorder the arguments, the parser will detect this as an invalid command.

In addition for adding of supplier, it seems like email address has to be a compulsory field (invalid command is shown), but in the UG it is an optional field. Should we still keep email address field as an optional field?

For adding of warehouses, if remarks field (which is optional) is left out, a java.lang.reflect.InvocationTargetException will be thrown. I think we missed out these cases, but no worries, let's fix them in v1.3 iteration! :)

**Comment by qlchan24** [comment]
For the part about commands only keeping the results from the last occurrence of a specified descriptor, I think it was originally not so much a bug but rather an intended outcome, as there are explicit test cases in the original AB3 to show that multiple descriptors of the same prefix will be accepted without error but only the last will be used. We can do an alternative approach though I would not think its absolutely necessary.

As for the case sensitivity, I guess we can discuss both the case sensitivity of the command syntax (command word/prefixes) and the user-supplied command arguments. For the command word at least, the case should not matter and we can make it case-insensitive to improve user experience, though I would think it's not a pressing issue as we can do without too.

For the redundant strings at the back of commands and the explicit ordering of arguments, it currently applies for those commands that dont actually use prefixes. For those with prefixes, changing it to allow redundant arguments may be a bit cumbersome, since currently all the arguments at the back will just be allocated to the last prefix, and we would require additional command-specific parsing to split the last prefix from the redundant strings if they would otherwise be parsed as invalid format for the last prefix. For those that don't, we can either make it explicit that redundant strings are allowed in the user guide for these commands or just don't accept them. Similarly for the ordering, we can either make these commands accept prefixes as well since they are multi-argument like the rest of the commands so that they disregard order, or we can explicitly state their difference in the user guide.
