### ISSUE TITLE
isSameSupplier/Warehouse method in supplier/warehouse class

### ISSUE THREAD

**Issue by tohyuting** [AY2021S1-CS2103-W14-4/tp#149]
I noticed that for supplier, it is a comparison by name and either matching phone/email address. However, for warehouse, it is only a comparison by name. While updating the edit command to reflect error when user tries to edit an entry with the same name as another existing supplier, I noticed this issue and have created new method to compare by Name only for supplier. In this case, should we standardise how we are comparing under isSameSupplier/Warehouse method?

**Comment by jeffreytjs** [comment]
Good spot, I think we could standardise these two methods. 

But it depends on how much flexibility we want to offer to users.

For now, supplier do allow for the same name but different phone and email while warehouse strictly do not allow for entries with same name.

**Comment by tohyuting** [comment]
I was thinking we can fix the method such that we do not allow same name because in reality, two suppliers/warehouses should not have the same name. However, different suppliers/warehouses can have the same address/email/phone if they are subsidiary companies of an organisation.

**Comment by jeffreytjs** [comment]
Then we don't really need to change because it's more possible that suppliers can have a common name and the code now does an additional check on their phone number to make sure that they are not the same person. Whereas warehouse just dont allow name clash at all

**Comment by tohyuting** [comment]
Would that be confusing for the user though, since now suppliers are allowed to have the same name yet this is not the case for warehouses? Otherwise to ensure there will not be any error, I will just leave the isSameNameSupplier method under Supplier class and depending on what conditions we are checking, we can call the appropriate method!

**Comment by jeffreytjs** [comment]
I would think it complements with this "different suppliers/warehouses can have the same address/email/phone if they are subsidiary companies of an organisation" but I'm thinking more of allowing more than one supplier named "George" with different phone rather than warehouses named "George Ptd Ltd".

**Comment by jeffreytjs** [comment]
Correct me if I made a mistake in understanding,
Current implementation:
Supplier:
Same name, different phone and email - allowed
Same name, same phone or email - not allowed

Warehouse:
Same name, different phone and address - not allowed
Same name, same phone or address - not allowed

I think it does make sense that warehouse names should not be allowed to have same name even though they can share common phone and address(maybe same building?)
However, if we disallow name clashes for suppliers it might inconvenient users because they have to manually rename the supplier instead of writing the differences under remarks. (E.g. "George Lim, 987654321" vs "George Lim, 91234567" which are two different person)

**Comment by tohyuting** [comment]
Yes you are right. Ah okay, I think I understand what you mean now. I was thinking of suppliers as companies (ending with Pte Ltd etc) instead of a single person (like George Lim). That is why I thought it would not be okay for suppliers to have same name as well. However, what you said make sense as well. In that case, would it be better to keep it as the original way of checking if suppliers are "the same"?

**Comment by jeffreytjs** [comment]
It would depend on how we write the user guide actually. but I figured supplier would be a contact person but users are free to interchange between company name and contact person in name and remarks. By my understanding it would be better to keep things as they are, but let's get the opinions of others as well!
